# reviewdog.yml
runner:
  golint-by-project-conf:
    cmd: golint $(go list ./... | grep -v /vendor/)
    format: golint
    level: warning
  govet-by-project-conf:
    cmd: go vet
    format: govet
    level: error
  custom-rdjson:
    cmd: cat ./_testdata/custom_rdjson.json
    name: custom-rdjson-by-project-conf
    format: rdjson
  test-project-conf:
    cmd: |
      echo '.reviewdog.yml:17: test project conf (errorformat)'
    level: info
    errorformat:
      - '%f:%l: %m'
